/**
 * ===========================================================================
 * THE LANGUAGE DATA TRAVELS WITH THE DEPLOY, OR THE CAPABILITY DOES NOT EXIST.
 * ===========================================================================
 *
 * Tesseract needs a trained model to read English, and where that model comes
 * from is an architectural decision rather than a detail. Three ways were
 * considered and two were rejected for reasons this repository has already
 * paid for once.
 *
 * NOT A CDN AT RUNTIME. `tesseract.js` fetches its model from jsDelivr by
 * default, which makes a core capability depend on a third party being
 * reachable at the moment a builder uploads. A deployment behind a strict
 * egress policy — which is the normal shape of a production network, and is
 * the shape of the environment this was built in, where that exact fetch
 * answers 403 — would simply never read a scan, intermittently, with the
 * failure looking like an unreadable document.
 *
 * NOT A BUCKET SOMEBODY SEEDS. Storing it in the project and fetching it from
 * there removes the third party and adds a provisioning step — and
 * `CLONE_PROVISIONING_GAPS.md` is a whole document about what happens then:
 * the rows a migration inserts do not travel, so a capability that depends on
 * a seeded object is absent on every clone while looking, from the code,
 * exactly like it is present.
 *
 * SO IT IS PART OF THE MODULE GRAPH. `supabase functions deploy --use-api`
 * uploads the modules a function imports and nothing else — a `.gz` sitting
 * beside them does not travel — so the model is generated into a TypeScript
 * module and imported. It is 2.95 MB compressed, about 3.9 MB as base64, and
 * it is imported DYNAMICALLY so only an invocation that actually meets a scan
 * pays to parse it.
 *
 * Generated by `npm run ocr:vendor-language`, never hand-edited, and checked
 * against its own sha256 on load.
 */

/** Where the decoded model is written, once per isolate. */
const LANG_DIR = '/tmp/ocr-lang';
const LANG_FILE = `${LANG_DIR}/eng.traineddata.gz`;

let resolved: string | null | undefined;

function decodeBase64(b64: string): Uint8Array {
  const binary = atob(b64);
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);
  return out;
}

/**
 * The directory holding `eng.traineddata.gz`, or null where the model could
 * not be provided.
 *
 * NULL IS A REAL ANSWER and the caller has one: a document whose text could
 * not be recognised is a document with no text, which this pipeline already
 * refuses honestly. It must never become a guess.
 */
export async function languageDataDirectory(): Promise<string | null> {
  if (resolved !== undefined) return resolved;
  try {
    // Already decoded by an earlier invocation on this isolate.
    const stat = await Deno.stat(LANG_FILE).catch(() => null);
    if (stat?.isFile && stat.size > 1_000_000) {
      resolved = LANG_DIR;
      return resolved;
    }
    /*
     * DYNAMIC, so a function that never meets a scan never parses four
     * megabytes of base64. The import is in its own statement so a missing
     * generated module is a caught failure rather than a load-time crash of
     * every function that imports the extractor.
     */
    const mod = await import('./english.generated.ts');
    const bytes = decodeBase64(mod.ENGLISH_TRAINEDDATA_GZ_BASE64);
    if (!bytes.length) { resolved = null; return resolved; }
    await Deno.mkdir(LANG_DIR, { recursive: true });
    await Deno.writeFile(LANG_FILE, bytes);
    resolved = LANG_DIR;
    return resolved;
  } catch {
    resolved = null;
    return resolved;
  }
}

/** For tests and the import log: is the model present in this build at all? */
export async function languageDataAvailable(): Promise<boolean> {
  return (await languageDataDirectory()) !== null;
}
