// GENERATED by scripts/ocr/vendor-engine.mjs — NEVER HAND-EDITED.
// The type of tesseractCore.generated.js; engineDriver.ts states the shape it calls.
declare const TesseractCore: (config?: Record<string, unknown>) => Promise<unknown>;
export default TesseractCore;
